export default {
	UPDATE_PAGE: 'UPDATE_PAGE',
	UPDATE_PASS: 'UPDATE_PASS',
	ADD_ITEM: 'ADD_ITEM',
	UPDATE_ITEMS: 'UPDATE_ITEMS',
	UPDATE_ITEM_TYPE: 'UPDATE_ITEM_TYPE',
	UPDATE_ITEM_CHECKED: 'UPDATE_ITEM_CHECKED',
	ADD_CHECKED_ITEM: 'ADD_CHECKED_ITEM',
	UPDATE_LINKED_ITEMS: 'UPDATE_LINKED_ITEMS',
	UPDATE_TIME_LEFT: 'UPDATE_TIME_LEFT',
	UPDATE_LOCK: 'UPDATE_LOCK',
};
